services:
  sushiwan_db:
    image: postgres:15-alpine
    container_name: sushiwan_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sushiwan_db
      POSTGRES_USER: sushiwan_admin
      POSTGRES_PASSWORD: SushiWan2024!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/init:/docker-entrypoint-initdb.d

  sushiwan_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sushiwan_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sushiwan.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - sushiwan_db

volumes:
  postgres_data:
    driver: local
